# Generated by Django 4.1.4 on 2022-12-21 09:41

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=200)),
                ('phone_code', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
                ('timezone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('mailing_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_of_start', models.DateTimeField(blank=True, null=True)),
                ('datetime_of_end', models.DateTimeField(blank=True, null=True)),
                ('text', models.CharField(max_length=1000)),
                ('mailing_filter', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_of_sending', models.DateField()),
                ('status', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_app.client')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_app.mailing')),
            ],
        ),
    ]
