# Generated by Django 4.1.4 on 2022-12-22 07:27

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_filter',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
